### ISSUE TITLE
Python script using the medium model doesn't work

### ISSUE THREAD

**Issue by vegandiet705** [facebookresearch/audiocraft#74]
I am trying to run the following python script, which uses the medium model:

```
import torchaudio
from audiocraft.models import MusicGen
from audiocraft.data.audio import audio_write

model = MusicGen.get_pretrained('medium')
model.set_generation_params(duration=8)  # generate 8 seconds.

descriptions = ['happy rock', 'energetic EDM', 'sad jazz']

wav = model.generate(descriptions)  # generates 3 samples.

for idx, one_wav in enumerate(wav):
    # Will save under {idx}.wav, with loudness normalization at -14 db LUFS.
    audio_write(f'{idx}', one_wav.cpu(), model.sample_rate, strategy="loudness")
```

I got the following logs:

```
Traceback (most recent call last):
  File "/home/worker/ai_music/fb_audiocraft/example.py", line 5, in <module>
    model = MusicGen.get_pretrained('medium')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/ai_music/fb_audiocraft/venv/lib/python3.11/site-packages/audiocraft/models/musicgen.py", line 96, in get_pretrained
    lm = load_lm_model(ROOT + f'{sig}.th', device=device)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/ai_music/fb_audiocraft/venv/lib/python3.11/site-packages/audiocraft/models/loaders.py", line 61, in load_lm_model
    model = builders.get_lm_model(cfg)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/ai_music/fb_audiocraft/venv/lib/python3.11/site-packages/audiocraft/models/builders.py", line 109, in get_lm_model
    return LMModel(
           ^^^^^^^^
  File "/home/worker/ai_music/fb_audiocraft/venv/lib/python3.11/site-packages/audiocraft/models/lm.py", line 167, in __init__
    self.transformer = StreamingTransformer(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/ai_music/fb_audiocraft/venv/lib/python3.11/site-packages/audiocraft/modules/transformer.py", line 596, in __init__
    layer_class(
  File "/home/worker/ai_music/fb_audiocraft/venv/lib/python3.11/site-packages/audiocraft/modules/transformer.py", line 444, in __init__
    super().__init__(d_model, num_heads, dim_feedforward, dropout,
  File "/home/worker/ai_music/fb_audiocraft/venv/lib/python3.11/site-packages/torch/nn/modules/transformer.py", line 450, in __init__
    self.linear2 = Linear(dim_feedforward, d_model, **factory_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/worker/ai_music/fb_audiocraft/venv/lib/python3.11/site-packages/torch/nn/modules/linear.py", line 96, in __init__
    self.weight = Parameter(torch.empty((out_features, in_features), **factory_kwargs))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 1.96 GiB total capacity; 1.37 GiB already allocated; 9.38 MiB free; 1.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Regarding my hardware, I have an AMD Ryzen 5 2500U processor with Radeon Vega Mobile Gfx and Nvidia GeForce GTX GPU (the appropriate drivers are already installed).

I'm on Ubuntu 20.04 OS.

Here is my output for nvidia-smi command:

```
Mon Jun 12 20:09:24 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   40C    P8    N/A /  N/A |      9MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1059      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      2035      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

Here is my output to `lscpu`:

```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   43 bits physical, 48 bits virtual
CPU(s):                          8
On-line CPU(s) list:             0-7
Thread(s) per core:              2
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       AuthenticAMD
CPU family:                      23
Model:                           17
Model name:                      AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
Stepping:                        0
Frequency boost:                 enabled
CPU MHz:                         1600.000
CPU max MHz:                     2000,0000
CPU min MHz:                     1600,0000
BogoMIPS:                        3992.53
Virtualization:                  AMD-V
L1d cache:                       128 KiB
L1i cache:                       256 KiB
L2 cache:                        2 MiB
L3 cache:                        4 MiB
NUMA node0 CPU(s):               0-7
```

Thanks in advance for any help

**Comment by vegandiet705** [comment]
The python script for the small model also gives the same problem

**Comment by catsled** [comment]
我认为你可以在CPU上运行，而不是在GPU上运行，我运行的是medium模型，差不多占用了12GB的VRAM

**Comment by 0RaMsY0** [comment]
Your GPU doesn't have enough ram.

**Comment by vegandiet705** [comment]
@0RaMsY0  Sorry, what is the PR ? Your link points to this issue.

**Comment by 0RaMsY0** [comment]
@vegandiet705 #64

**Comment by vegandiet705** [comment]
@0RaMsY0 Thank you, now I can run the small model locally on CPU. But still can't run the medium model (I get the `Killed` output).

Is there some hack to run the medium and the large model on my CPU ? I don't mind if it takes a lot of time.

**Comment by 0RaMsY0** [comment]
@vegandiet705  you can run the large model in [Google Colab](https://colab.research.google.com) they give you a GPU with like 15GB of VRAM and 12GB of system ram so it is more then enough to run it, i tried it and it works fine.

**Comment by vegandiet705** [comment]
@0RaMsY0 Thanks a lot for the help. However, I had already managed to run it on Colab. I was wondering if there were some hacks to run the larger models in a CPU with limited RAM. To give more details, I'm interested in using the models in an embedded application without access to the internet. The machine I have now is limited in RAM and I can't buy a more powerful machine right now.

**Comment by 0RaMsY0** [comment]
@vegandiet705  Personally i don't know. But i think if you have a fast SSD you can create a swap file and load the model there with that you will be able to use it i guess. I don't know how exactly but you can do more research on that.

**Comment by jbmaxwell** [comment]
I'm getting a CUDA Out of memory error when trying to train `musicgen-medium` with `encodec_32khz`  on 2x A100 40GB GPUs... Wha??? I bumped the batch size right down to 2, but same error. When idle, `nvidia-smi` reports `7MiB / 40960MiB` per GPU.

**Comment by nakshatravyas** [comment]
> I'm getting a CUDA Out of memory error when trying to train `musicgen-medium` with `encodec_32khz` on 2x A100 40GB GPUs... Wha??? I bumped the batch size right down to 2, but same error. When idle, `nvidia-smi` reports `7MiB / 40960MiB` per GPU.

from where you can reduce the batch size. Can you tell me?
